import { type ThemeConfig } from '../types';

export const THEMES: ThemeConfig[] = [
  {
    id: 'editorial-stone',
    name: 'Editorial Stone',
    bgType: 'solid',
    bgColor: '#FAF9F6',
    textColor: '#181817',
    subtextColor: '#71717A',
    cardBg: '#FFFFFF',
    cardText: '#181817',
    cardBorder: '1px solid #E5E5E0',
    cardHover: '#F9FAFA',
    cardRadius: 'xl',
    accentColor: '#B45309',
    fontFamily: 'sans',
    isDark: false,
  },
  {
    id: 'obsidian-noir',
    name: 'Obsidian Noir',
    bgType: 'solid',
    bgColor: '#0F172A',
    textColor: '#E2E8F0',
    subtextColor: '#A8B4C7',
    cardBg: '#1E293B',
    cardText: '#E2E8F0',
    cardBorder: '1px solid #334155',
    cardHover: '#273548',
    cardRadius: 'xl',
    accentColor: '#1D4ED8',
    fontFamily: 'sans',
    isDark: true,
  },
  {
    id: 'tokyo-cyber',
    name: 'Tokyo Neon',
    bgType: 'gradient',
    bgColor: '#0A0A15',
    bgGradient: 'linear-gradient(180deg, #0A0A15 0%, #1e2a42 50%, #0f172a 100%)',
    textColor: '#F8FAFC',
    subtextColor: '#94A3B8',
    cardBg: 'rgba(255, 255, 255, 0.05)',
    cardText: '#F8FAFC',
    cardBorder: '1px solid rgba(56, 179, 248, 0.3)',
    cardHover: 'rgba(56, 179, 248, 0.12)',
    cardRadius: 'xl',
    accentColor: '#EC4899',
    fontFamily: 'sans',
    isDark: true,
  },
  {
    id: 'nordic-minimal',
    name: 'Nordic Clean',
    bgType: 'solid',
    bgColor: '#FFFFFF',
    textColor: '#0F172A',
    subtextColor: '#64748B',
    cardBg: '#F8FAFC',
    cardText: '#0F172A',
    cardBorder: '1px solid #E5E5E0',
    cardHover: '#F1F5F9',
    cardRadius: 'xl',
    accentColor: '#1D4ED8',
    fontFamily: 'sans',
    isDark: false,
  },
  {
    id: 'sunset-amber',
    name: 'Amber Hour',
    bgType: 'gradient',
    bgColor: '#FFFBEB',
    bgGradient: 'linear-gradient(180deg, #FEF3C7 0%, #FDE68A 100%)',
    textColor: '#451A03',
    subtextColor: '#78350F',
    cardBg: '#FFFFFF',
    cardText: '#451A03',
    cardBorder: '1px solid rgba(217, 119, 6, 0.25)',
    cardHover: '#FFFBEB',
    cardRadius: 'xl',
    accentColor: '#92400E',
    fontFamily: 'sans',
    isDark: false,
  },
  {
    id: 'velvet-plum',
    name: 'Velvet Atelier',
    bgType: 'solid',
    bgColor: '#1E213B',
    textColor: '#F8FAFC',
    subtextColor: '#C084FC',
    cardBg: '#2D1B43',
    cardText: '#F8FAFC',
    cardBorder: '1px solid #4A2C5A',
    cardHover: '#372440',
    cardRadius: 'xl',
    accentColor: '#D8B4FE',
    fontFamily: 'sans',
    isDark: true,
  },
  {
    id: 'brutalist-mono',
    name: 'Neo Brutalist',
    bgType: 'solid',
    bgColor: '#FAF9F6',
    textColor: '#181817',
    subtextColor: '#6B7280',
    cardBg: '#FFFFFF',
    cardText: '#181817',
    cardBorder: '2px solid #181817',
    cardHover: '#F3F4F6',
    cardRadius: 'none',
    accentColor: '#181817',
    fontFamily: 'sans',
    isDark: false,
  },
  {
    id: 'forest-canopy',
    name: 'Forest Canopy',
    bgType: 'gradient',
    bgColor: '#0B1A14',
    bgGradient: 'linear-gradient(180deg, #0B1A14 0%, #16332e 50%, #102a1e 100%)',
    textColor: '#E8F5E9',
    subtextColor: '#81C784',
    cardBg: 'rgba(255, 255, 255, 0.05)',
    cardText: '#E8F5E9',
    cardBorder: '1px solid rgba(76, 175, 80, 0.3)',
    cardHover: 'rgba(76, 175, 80, 0.12)',
    cardRadius: 'xl',
    accentColor: '#4CAF50',
    fontFamily: 'sans',
    isDark: true,
  },
  {
    id: 'coral-reef',
    name: 'Coral Reef',
    bgType: 'gradient',
    bgColor: '#FFF5F5',
    bgGradient: 'linear-gradient(180deg, #FFF1F2 0%, #FFE4E6 50%, #FECDD3 100%)',
    textColor: '#881337',
    subtextColor: '#BE185D',
    cardBg: '#FFFFFF',
    cardText: '#881337',
    cardBorder: '1px solid rgba(244, 63, 94, 0.2)',
    cardHover: '#FFF1F2',
    cardRadius: 'xl',
    accentColor: '#9F1239',
    fontFamily: 'sans',
    isDark: false,
  },
  {
    id: 'midnight-ink',
    name: 'Midnight Ink',
    bgType: 'solid',
    bgColor: '#0F172A',
    textColor: '#E2E8F0',
    subtextColor: '#A8B4C7',
    cardBg: '#1E293B',
    cardText: '#E2E8F0',
    cardBorder: '1px solid #334155',
    cardHover: '#273548',
    cardRadius: 'xl',
    accentColor: '#0369A1',
    fontFamily: 'sans',
    isDark: true,
  },
  {
    id: 'sahara-dune',
    name: 'Sahara Dune',
    bgType: 'gradient',
    bgColor: '#FDFAF5',
    bgGradient: 'linear-gradient(180deg, #FDFAF5 0%, #F5EDE0 50%, #EADBC8 100%)',
    textColor: '#3E2C1C',
    subtextColor: '#8B6914',
    cardBg: '#FFFFFF',
    cardText: '#3E2C1C',
    cardBorder: '1px solid rgba(194, 139, 56, 0.25)',
    cardHover: '#FAF3E6',
    cardRadius: 'xl',
    accentColor: '#8B5E1A',
    fontFamily: 'sans',
    isDark: false,
  }
];
