export const uiArabic: Record<string, string> = {
  'Reload this page to try again.': 'أعد تحميل الصفحة للمحاولة مجدداً.',
  'Could not load data. Reopen this tab to retry.': 'تعذّر تحميل البيانات. افتح هذا التبويب مجدداً لإعادة المحاولة.',
  'Uploading...': 'جارٍ الرفع…', 'Upload Avatar Image': 'رفع صورة الملف', 'Dark': 'داكن', 'Light': 'فاتح', 'Square': 'مربّع', 'Pill': 'بيضاوي',
  'loading': 'جارٍ التحميل', 'Current Plan': 'الخطة الحالية', 'Downgrade': 'إدارة الاشتراك', 'Select Pro': 'اختيار Pro', 'Select Studio': 'اختيار Studio', 'Analytics': 'التحليلات', 'Published page': 'الصفحة المنشورة', 'Published autosave': 'حفظ مباشر للصفحة المنشورة', 'Changes save directly to the published page. Unpublished pages are hidden; Liinx does not keep a separate draft revision.': 'تُحفظ التغييرات مباشرةً على الصفحة المنشورة. الصفحات غير المنشورة مخفية؛ ولا يحتفظ Liinx بإصدار مسودة منفصل.', 'Saved': 'تم الحفظ', 'Studio': 'Studio',
  '✓ Pixel settings saved!': 'تم حفظ إعدادات التتبع', 'Save Tracking IDs': 'حفظ معرّفات التتبع', 'Checking DNS...': 'جارٍ فحص DNS…', 'Verify DNS': 'التحقق من DNS', 'Global availability monitoring': 'مراقبة التوفر والجاهزية عالمياً',
  'Save Domain': 'حفظ النطاق', '✓ Custom styling saved!': 'تم حفظ المظهر المخصص', 'Save Custom CSS & Fonts': 'حفظ CSS والخطوط',
  'CONNECTED': 'متصل', 'DISCONNECTED': 'غير متصل', 'Syncing...': 'جارٍ المزامنة…', 'Sync Now': 'المزامنة الآن', 'ENABLED': 'مفعّل', 'PAUSED': 'متوقف',
  'Creating...': 'جارٍ الإنشاء…', 'Create Profile': 'إنشاء ملف', 'API Key Generated': 'تم إنشاء مفتاح API', 'Generate Studio API Key': 'إنشاء مفتاح API',
  'Copied': 'تم النسخ', 'Copy': 'نسخ', 'Generating...': 'جارٍ الإنشاء…', 'Downloading...': 'جارٍ التنزيل…', 'Download PNG': 'تنزيل PNG',
  'Contact us': 'تواصل معنا', 'Build your micro-site': 'أنشئ موقعك المصغر', 'Choose your aesthetic': 'اختر مظهر صفحتك', 'Saving to database...': 'جارٍ الحفظ…',
  'Creator / Influencer': 'صانع محتوى أو مؤثّر', 'Photographer / Visual Artist': 'مصوّر أو فنان بصري', 'Musician / Producer / DJ': 'موسيقي أو منتج موسيقي',
  'Developer / Designer / Studio': 'مطور أو مصمم أو استوديو', 'Coach / Consultant / Wellness': 'مدرب أو مستشار أو مختص بالعافية', 'Small Business / Brand': 'نشاط تجاري أو علامة تجارية',
  'Retry': 'إعادة المحاولة',
  'Loading your profile…': 'جارٍ تحميل ملفك…',
  'Could not load your profile. No demo data is being shown.': 'تعذّر تحميل ملفك. لا يتم عرض بيانات تجريبية.',
  'Sign in to edit your page': 'سجّل الدخول لتعديل صفحتك',
  'Changes are not saved. Check your connection and retry.': 'لم تُحفظ التغييرات. تحقق من اتصالك وأعد المحاولة.',
  'Delete this block?': 'هل تريد حذف هذه الكتلة؟',
  'Switch Profile (': 'تبديل الملف (',
  'Live Profile': 'الملف المنشور',
  'Supports JPG, PNG, WEBP up to 5MB. Stored directly on server.': 'يدعم JPG وPNG وWEBP حتى ٥ ميغابايت. تُحفظ الملفات على الخادم.',
  'Remove social link': 'حذف رابط التواصل',
  'Email': 'البريد الإلكتروني', 'Add': 'إضافة', 'clicks': 'نقرات', 'Move up': 'نقل للأعلى', 'Move down': 'نقل للأسفل',
  'Delete block': 'حذف الكتلة', 'Title': 'العنوان', 'Destination URL': 'رابط الوجهة', 'Artist Name': 'اسم الفنان', 'Artist / Band': 'الفنان أو الفرقة',
  'Video Stream URL': 'رابط الفيديو', 'Button CTA Text': 'نص الزر', 'Subtitle Note': 'النص الفرعي', 'Supporting text...': 'نص توضيحي…', 'Badge Tag': 'الشارة',
  'e.g. NEW, SALE, LISTEN': 'مثال: جديد، تخفيض، استمع', 'Link Scheduling & Time-Release': 'جدولة نشر الروابط', 'PRO FEATURE': 'ميزة Pro',
  'Publish (Start Date/Time):': 'النشر (تاريخ ووقت البدء):', 'Unpublish (End Date/Time):': 'إيقاف النشر (تاريخ ووقت الانتهاء):',
  'Upgrade to Pro to automatically schedule links to go live and expire at specific dates and times.': 'انتقل إلى Pro لجدولة نشر الروابط وإيقافها في أوقات محددة.',
  'Album Cover Image URL': 'رابط صورة غلاف الألبوم', 'Streaming Link': 'رابط الاستماع', 'Thumbnail Preview Image URL': 'رابط الصورة المصغرة',
  'Newsletter Description': 'وصف النشرة البريدية', 'What will subscribers get?': 'ما الذي سيحصل عليه المشتركون؟', 'Folder Links': 'روابط المجلد', 'Add Item': 'إضافة عنصر',
  'Choose from carefully crafted aesthetic profiles. Every palette is built with strong contrast and responsive tokens.': 'اختر مظهراً جاهزاً ثم خصّصه لصفحتك.',
  'font': 'الخط', 'Clicks per view': 'نقرات لكل زيارة', 'Live logged': 'مسجّلة', 'Views': 'الزيارات', 'Clicks': 'النقرات', 'clicks (': 'نقرات (',
  'UTM Campaign & Traffic Attribution': 'الحملات ومصادر الزيارات', 'Source / Medium / Campaign': 'المصدر / الوسيط / الحملة',
  'No UTM parameters recorded yet. Append': 'لم تُسجّل وسوم حملات بعد. أضف', 'to your bio URL to start tracking!': 'إلى رابط صفحتك لبدء التتبع.',
  'views': 'زيارات', 'Current tier:': 'الخطة الحالية:', 'ACTIVE': 'نشطة', 'Free': 'مجاني', 'Core links, analytics & bio': 'الروابط والإحصاءات والملف الشخصي',
  'POPULAR': 'شائعة', 'Custom domain and branding controls': 'نطاق مخصص والتحكم بشارة المنصة', 'Studio VIP': 'Studio',
  'Custom CSS and REST API': 'تخصيص CSS وواجهة REST API', 'Remove the "Made with LIINX" badge from your bio page and footer.': 'أزل شارة «صُنع باستخدام LIINX» من صفحتك وتذييلها.',
  'Upgrade to Pro or Studio to completely remove all LIINX branding badges.': 'انتقل إلى Pro أو Studio لإزالة شارات LIINX.',
  'Analytics & Retargeting Pixels': 'الإحصاءات وأدوات إعادة الاستهداف',
  'Connect your Google Analytics 4 Measurement ID and Meta Pixel to track visitors and run retargeting ads.': 'اربط معرّف Google Analytics 4 وأداة Meta لتتبع الزيارات. تحقّق من متطلبات موافقة الزائر قبل التفعيل.',
  'Google Analytics 4 Measurement ID': 'معرّف قياس Google Analytics 4', 'Found in GA4 Admin > Data Streams > Measurement ID': 'من إعدادات GA4: مصادر البيانات ثم معرّف القياس',
  'Meta (Facebook) Pixel ID': 'معرّف أداة Meta (Facebook)', 'e.g. 123456789012345': 'مثال: 123456789012345', 'Found in Meta Events Manager > Data Sources': 'من مدير أحداث Meta ثم مصادر البيانات',
  'Link your own domain or subdomain (e.g.': 'اربط نطاقك أو نطاقاً فرعياً (مثل', ') directly to your bio page.': ') بصفحتك.', 'PRO / STUDIO': 'Pro / Studio',
  'AVAILABLE': 'متاح', 'Domain / Subdomain Name': 'اسم النطاق أو النطاق الفرعي', 'e.g. links.sarahcreator.com': 'مثال: links.example.com',
  'DNS Configuration Instructions:': 'تعليمات إعداد DNS:', 'Add a': 'أضف سجل', 'record at your DNS provider pointing to:': 'لدى مزوّد DNS يشير إلى:', 'Copy Target': 'نسخ الهدف',
  'Custom CSS & Custom Webfonts': 'تخصيص CSS وخطوط الويب', 'Inject custom stylesheet overrides and Google Fonts to match your brand guide.': 'أضف تنسيقات CSS وخطوط Google لتناسب هويتك البصرية.',
  'Google Fonts / Webfont Stylesheet URL': 'رابط ملف تنسيق خطوط الويب أو Google Fonts', 'Custom CSS Overrides': 'تنسيقات CSS المخصصة', 'Scoped to #public-bio-view': 'ضمن العنصر #public-bio-view',
  'Developer & REST API Access': 'المطورون والوصول إلى REST API', 'Manage your LIINX link bio programmatically via our public REST API v1.': 'أدر صفحتك برمجياً باستخدام REST API v1.',
  'STUDIO TIER ONLY': 'خطة Studio فقط', 'API ENABLED': 'واجهة API مفعّلة',
  'REST API keys and programmatic block automation require a Studio subscription. Upgrade to unlock direct API access.': 'يتطلب إنشاء مفاتيح REST API وإدارة الكتل برمجياً اشتراك Studio.',
  'Active API Keys': 'مفاتيح API النشطة', 'No API keys generated yet. Click "Generate Key" to create your first API credential.': 'لا توجد مفاتيح بعد. اضغط «إنشاء مفتاح» للبدء.',
  'Revoke': 'إلغاء المفتاح', 'Sample API Request': 'مثال لطلب API', 'Instagram Caption Auto-Sync': 'مزامنة روابط منشورات إنستغرام',
  'Automatically pull and create link buttons whenever you mention links in post captions.': 'استخرج الروابط من نصوص المنشورات بعد إعداد تكامل إنستغرام.',
  'synced links active': 'روابط متزامنة نشطة', 'Disconnect': 'فصل الحساب', 'Auto-sync on incoming Webhooks:': 'المزامنة عند استقبال إشعارات Webhook:',
  'Meta Instagram OAuth Setup Required': 'يلزم إعداد تسجيل الدخول عبر Meta لإنستغرام', 'To connect your live Instagram account, server administrators must configure': 'لربط حسابك، يجب على مسؤول الخادم إعداد',
  'and': 'و', 'in the server environment.': 'في بيئة الخادم.', 'Live Caption Parser & Link Ingest is available below without OAuth.': 'يمكنك استخراج الروابط من نص منشور أدناه دون ربط الحساب.',
  'Connect your Instagram account': 'اربط حساب إنستغرام', 'Authorize via official Meta Graph API to enable automatic post polling & real-time webhook updates.': 'امنح الإذن عبر Meta Graph API بعد إعداد التطبيق لاستقبال تحديثات المنشورات.',
  'Live Caption Parser & Post Ingest': 'استخراج الروابط من نص المنشور', 'Fill sample caption': 'إدراج نص تجريبي',
  "Paste any Instagram caption containing links to extract & add to your bio (e.g. 'Presave the single on Spotify: https://...')": 'ألصق نص منشور يحتوي على روابط لاستخراجها وإضافتها إلى صفحتك…',
  'Test Parser': 'اختبار الاستخراج', 'Extract & Add Link to Bio': 'استخراج الروابط وإضافتها', 'Newsletter Email Subscribers': 'مشتركو النشرة البريدية',
  "Real subscribers collected directly from your page's newsletter blocks.": 'المشتركون الذين سجّلوا عبر نماذج النشرة في صفحتك.', 'total': 'الإجمالي', 'Download CSV': 'تنزيل CSV',
  'No subscribers collected yet. Add a Newsletter block to your page to start capturing leads!': 'لا يوجد مشتركون بعد. أضف نموذج نشرة بريدية إلى صفحتك للبدء.',
  'Create New Bio Profile': 'إنشاء ملف جديد', 'Add another project, brand, or persona under your account.': 'أضف مشروعاً أو علامة تجارية أو ملفاً آخر إلى حسابك.',
  'Handle (Username)': 'اسم المستخدم', 'My Other Brand': 'علامتي الأخرى', 'Cancel': 'إلغاء', 'Make sure to copy your API key now.': 'انسخ مفتاح API الآن.',
  "You won't be able to see it again! Store it in an environment variable or secrets manager.": 'لن تتمكن من رؤيته مرة أخرى. احفظه في متغير بيئة أو مدير أسرار.',
  'Your Live Secret Key': 'مفتاحك السري', 'Done': 'تم', 'Key Name / Description': 'اسم المفتاح أو وصفه', 'e.g., Zapier Sync, Mobile App Integration': 'مثال: مزامنة Zapier أو تطبيق الهاتف',
  'Give your API key a recognizable name so you can track where it is being used.': 'اختر اسماً واضحاً للمفتاح لتعرف أين يُستخدم.',
  'Creator pages & booking': 'صفحات شخصية وحجوزات', 'Custom Domains': 'نطاقات مخصصة', 'About': 'عن المنصة', 'Creator Handbook': 'دليل صانع المحتوى',
  'Switch from Linktree': 'الانتقال من Linktree', 'Public REST API': 'واجهة REST API', 'Security': 'الأمان', 'Privacy controls': 'إعدادات الخصوصية', 'Account-owned content': 'محتوى يملكه صاحب الحساب',
  'One-Click Linktree Importer': 'استيراد روابط Linktree', 'Import links': 'استيراد الروابط', 'Preview and choose links before importing': 'عاين الروابط واخترها قبل الاستيراد',
  'Linktree or Beacons Profile URL': 'رابط صفحة Linktree أو Beacons', 'Supports Linktree, Beacons, and public bio profiles.': 'يدعم صفحات Linktree وBeacons وصفحات الروابط العامة.',
  'links discovered': 'روابط مكتشفة', 'Back': 'رجوع', 'Importing': 'جارٍ استيراد', 'Links...': 'روابط…', 'Import': 'استيراد', 'Links into LIINX': 'روابط إلى LIINX',
  'Micro-site builder': 'منشئ المواقع المصغرة', 'Available': 'متاح', 'Log out': 'تسجيل الخروج', 'Toggle menu': 'فتح أو إغلاق القائمة', 'Logged in as @': 'مسجّل الدخول باسم @', 'Log Out': 'تسجيل الخروج',
  'Share bio link': 'مشاركة رابط الصفحة', 'Copy bio link': 'نسخ رابط الصفحة', 'Link copied to clipboard': 'تم نسخ الرابط', 'Verified Creator': 'صانع محتوى موثّق',
  'Listen track': 'الاستماع للمقطع', 'items': 'عناصر', 'Post': 'منشور', "You're on the list! Welcome.": 'تم اشتراكك في القائمة. أهلاً بك.',
  'Unable to load creator page': 'تعذّر تحميل الصفحة', 'Go to Homepage': 'الانتقال للرئيسية', 'Creator page not found': 'الصفحة غير موجودة', 'The handle': 'اسم المستخدم',
  "hasn't been claimed yet or does not exist.": 'غير مسجّل أو غير موجود.', 'Claim this handle': 'احجز هذا الاسم', 'Verified Profile': 'ملف موثّق', 'Play track': 'تشغيل المقطع', 'links': 'روابط',
  'Enter your email address': 'أدخل بريدك الإلكتروني', 'Could not copy link. Copy the address from the live page.': 'تعذّر نسخ الرابط. انسخ العنوان من الصفحة المنشورة.',
  'Could not download QR code. Please retry.': 'تعذّر تنزيل رمز QR. أعد المحاولة.', 'Close modal': 'إغلاق النافذة', 'Dynamic QR Code': 'رمز QR للصفحة',
  "'s profile anywhere in the physical world": 'عبر رمز QR', 'QR Tint:': 'لون الرمز:', 'Everything your work deserves.': 'أدوات لعرض أعمالك.', 'Built into one platform.': 'في منصة واحدة.',
  "We'd love to hear from you.": 'يسعدنا تواصلك.',
  'Have a question about custom domains, agency partnerships, or migration from another platform? Send our creator concierge team a message.': 'لديك سؤال عن النطاقات أو الانتقال من منصة أخرى؟ أرسل لنا رسالة.',
  'Have a question about custom domains, partnerships, or migration from another platform? Send our support team a message.': 'لديك سؤال عن النطاقات أو الشراكات أو الانتقال من منصة أخرى؟ أرسل لفريق الدعم رسالة.',
  'Your message has been saved. No response time is guaranteed.': 'تم حفظ رسالتك. لا يوجد وقت استجابة مضمون.', 'Your message was not saved. Please retry.': 'لم تُحفظ رسالتك. أعد المحاولة.',
  'Return Home': 'العودة للرئيسية', 'Tell us about your project or inquiry...': 'أخبرنا عن مشروعك أو استفسارك…', 'Welcome back to your Studio': 'مرحباً بعودتك إلى الاستوديو',
  'Or': 'أو', 'claim a new handle and create your page': 'احجز اسماً جديداً وأنشئ صفحتك', 'Email address': 'البريد الإلكتروني', 'Password': 'كلمة المرور',
  'Already have an account?': 'لديك حساب بالفعل؟', 'Sign in here': 'سجّل الدخول هنا', 'Choose your handle': 'اختر اسم المستخدم', 'yourname': 'اسم المستخدم',
  'Your live link will be': 'سيكون رابط صفحتك', 'Choose password': 'اختر كلمة المرور', 'At least 8 characters': '٨ أحرف على الأقل', 'What are you building?': 'ما نوع صفحتك؟',
  'Preview only. Open the live page to subscribe.': 'هذه معاينة فقط. افتح الصفحة المنشورة للاشتراك.',
  'View page': 'معاينة الصفحة',
  'Design-first mini-sites': 'مواقع مصغرة تركز على التصميم',
  'Editorial Stone': 'حجر تحريري',
  'Obsidian Noir': 'أوبسيديان داكن',
  'Tokyo Neon': 'طوكيو نيون',
  'Nordic Clean': 'نورديك نقي',
  'Amber Hour': 'ساعة العنبر',
  'Velvet Atelier': 'أتيليه مخملي',
  'Neo Brutalist': 'نيو بروتاليست',
  'Forest Canopy': 'مظلة الغابة',
  'Coral Reef': 'شعب مرجانية',
  'Midnight Ink': 'حبر منتصف الليل',
  'Sahara Dune': 'كثبان الصحراء'
};
